Repository roberto-butti/some-drops-of-php, pull requests merged in 2023-10, with the labels that each got.

#1 Review chapter 2
  src/content/docs/02-array/00-arr-intro.md
  src/content/docs/02-array/01-arr-array_map.md
  src/content/docs/02-array/02-arr-join.md
  src/content/docs/02-array/03-arr-key_exists.md
  src/content/docs/02-array/04-arr-in_array.md
  src/content/docs/02-array/05-arr-array_merge.md
  src/content/docs/02-array/06-arr-range.md
  src/content/docs/02-array/07-arr-compact.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#2 Review chapter 1
  src/content/docs/01-system/00-sys-intro.md
  src/content/docs/01-system/01-sys-phpversion.md
  src/content/docs/01-system/02-sys-phpuname.md
  src/content/docs/01-system/03-sys-memory_get_usage.md
  src/content/docs/01-system/04-sys-getenv.md
  src/content/docs/01-system/05-sys-exit.md
  src/content/docs/01-system/06-sys-register_shutdown_function.md
  src/content/docs/01-system/07-sys-pcntl_signal.md
  src/content/docs/01-system/08-sys-get_loaded_extensions.md
  src/content/docs/01-system/09-sys-version_compare.md
  src/content/docs/01-system/10-sys-getmypid.md
  src/content/docs/01-system/11-sys-getrusage.md
  src/content/docs/01-system/12-sys-microtime.md
  src/content/docs/01-system/13-sys-hrtime.md
  src/content/docs/01-system/14-sys-sys_get_temp_dir.md
  src/content/docs/01-system/15-sys-tempnam.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#3 reviewing chapter 3
  astro.config.mjs
  src/content/docs/03-vars/00-var-intro.md
  src/content/docs/03-vars/01-var-gettype.md
  src/content/docs/03-vars/02-var-directory_separator.md
  src/content/docs/03-vars/03-var-php_eol.md
  src/content/docs/03-vars/04-var-get_object_vars.md
Labels: hacktoberfest, hacktoberfest-accepted

#4 review chapter 4
  astro.config.mjs
  src/content/docs/04-functions/00-fns-intro.md
  src/content/docs/04-functions/01-fns-anonymous.md
  src/content/docs/04-functions/02-fns-arrowfunction.md
Labels: hacktoberfest, hacktoberfest-accepted

#5 Review chapter 5 and 6
  astro.config.mjs
  src/content/docs/05-string/00-str-intro.md
  src/content/docs/05-string/01-str-str_pad.md
  src/content/docs/05-string/02-str-mb_convert_case.md
  src/content/docs/05-string/03-str-sscanf.md
  src/content/docs/05-string/04-str-sprintf.md
  src/content/docs/05-string/05-str-ctype_alpha.md
  src/content/docs/05-string/06-str-ctype_digit.md
  src/content/docs/05-string/07-str-ctype_lower.md
  src/content/docs/05-string/08-str-uniqid.md
  src/content/docs/05-string/09-str-serialize.md
  src/content/docs/05-string/10-str-unserialize.md
  src/content/docs/05-string/11-str-gzcompress.md
  src/content/docs/05-string/12-str-gzuncompress.md
  src/content/docs/05-string/13-str-trim.md
  src/content/docs/05-string/14-str-json_decode.md
  src/content/docs/05-string/15-str-vsprintf.md
  src/content/docs/06-file/00-fil-intro.md
  src/content/docs/06-file/01-fil-stat.md
  src/content/docs/06-file/02-fil-scandir.md
  src/content/docs/06-file/03-fil-pathinfo.md
  src/content/docs/06-file/04-fil-mkdir.md
  src/content/docs/06-file/05-fil-md5_file.md
  src/content/docs/06-file/06-fil-glob.md
  src/content/docs/06-file/07-fil-readdir.md
Labels: hacktoberfest

#6 Examples for chapter 1
  examples/01-system/01-sys-phpversion.php
  examples/01-system/02-sys-phpuname.php
  examples/01-system/03-sys-memory_get_usage.php
  examples/01-system/04-sys-getenv.php
  examples/01-system/05-sys-exit.php
  examples/01-system/06-sys-register_shutdown_function.php
  examples/01-system/07-sys-pcntl_signal.php
  examples/01-system/08-sys-get_loaded_extensions.php
  examples/01-system/09-sys-version_compare.php
  pint.json
Labels: hacktoberfest

#7 more examples for chapter 1
  examples/01-system/10-sys-getmypid.php
  examples/01-system/11-sys-getrusage.php
  examples/01-system/12-sys-microtime.php
  examples/01-system/13-sys-hrtime.php
  examples/01-system/14-sys-sys_get_temp_dir.php
  examples/01-system/15-sys-tempnam.php
Labels: hacktoberfest, hacktoberfest-accepted

#9 examples for chapter 2
  examples/02-arr/01-arr-array_map.php
  examples/02-arr/02-arr-join.php
  examples/02-arr/03-arr-key_exists.php
  examples/02-arr/04-arr-in_array.php
  examples/02-arr/05-arr-array_merge.php
  examples/02-arr/06-arr-range.php
  examples/02-arr/07-arr-compact.php
Labels: hacktoberfest

#10 examples chapter 3
  examples/03-vars/01-var-gettype.php
  examples/03-vars/02-var-directory_separator.php
  examples/03-vars/03-var-php_eol.php
  examples/03-vars/04-var-get_object_vars.php
Labels: hacktoberfest, hacktoberfest-accepted

#11 Examples for chapters 4, 5, 6
  examples/02-array/01-arr-array_map.php
  examples/02-array/02-arr-join.php
  examples/02-array/03-arr-key_exists.php
  examples/02-array/04-arr-in_array.php
  examples/02-array/05-arr-array_merge.php
  examples/02-array/06-arr-range.php
  examples/02-array/07-arr-compact.php
  examples/04-functions/01-fns-anonymous.php
  examples/04-functions/02-fns-arrowfunction.php
  examples/05-string/01-str-str_pad.php
  examples/05-string/02-str-mb_convert_case.php
  examples/05-string/03-str-sscanf.php
  examples/05-string/04-str-sprintf.php
  examples/05-string/05-str-ctype_alpha.php
  examples/05-string/06-str-ctype_digit.php
  examples/05-string/07-str-ctype_lower.php
  examples/05-string/08-str-uniqid.php
  examples/05-string/09-str-serialize.php
  examples/05-string/10-str-unserialize.php
  examples/05-string/11-str-gzcompress.php
  examples/05-string/12-str-gzuncompress.php
  examples/05-string/13-str-trim.php
  examples/05-string/14-str-json_decode.php
  examples/05-string/15-str-vsprintf.php
  examples/06-file/01-fil-stat.php
  examples/06-file/02-fil-scandir.php
  examples/06-file/03-fil-pathinfo.php
  examples/06-file/04-fil-mkdir.php
  examples/06-file/05-fil-md5_file.php
  examples/06-file/06-fil-glob.php
  examples/06-file/07-fil-readdir.php
  examples/06-file/08-fil-file.php
Labels: hacktoberfest, hacktoberfest-accepted

#12 Add issue template for asking the creation of a new function
  .github/ISSUE_TEMPLATE/add-new-function.md
  pint.json
Labels: hacktoberfest, hacktoberfest-accepted

#14 Update 08-fil-file.php
  examples/06-file/08-fil-file.php
Labels: hacktoberfest, hacktoberfest-accepted

#18 Modification and Addition of Optional Arguments for Array_map()
  src/content/docs/02-array/01-arr-array_map.md
Labels: hacktoberfest, hacktoberfest-accepted
